FuturFusion/migration-manager

cmd/migration-managerd/internal/api/workers.go, internal/target/incus.go
In my previous PR I missed that this helper returns an error if no file is found, so this moves them to after checking the VM type.
=> Only fetch VirtIO drivers ISO for Windows VMs

cmd/migration-manager/internal/cmds/instance.go, cmd/migration-manager/internal/cmds/source.go, cmd/migration-manager/internal/cmds/target.go, cmd/migration-managerd/internal/api/api_queue.go, cmd/migration-managerd/internal/api/api_source.go, cmd/migration-managerd/internal/api/api_target.go, cmd/migration-managerd/internal/api/api_target_test.go, cmd/migration-managerd/internal/api/workers.go, internal/db/update.go, internal/migration/repo/sqlite/instance_test.go, internal/migration/repo/sqlite/source.go, internal/migration/repo/sqlite/source_test.go, internal/migration/repo/sqlite/target.go, internal/migration/repo/sqlite/target_test.go, internal/migration/source_model.go, internal/migration/source_service_test.go, internal/migration/target_model.go, internal/migration/target_service_test.go, internal/source/common.go, internal/source/vmware.go, internal/target/common.go, internal/target/incus.go, internal/target/interface.go, shared/api/source.go, shared/api/target.go
This moves most properties for source and targets into json objects that can contain type-specific values without needing to then also worry about future database schema updates.
=> Move most Source and Target properties into type-specific structs

cmd/migration-manager-worker/internal/worker/worker.go, cmd/migration-manager-worker/worker_test.go, cmd/migration-managerd/internal/api/api_queue.go, cmd/migration-managerd/internal/api/daemon.go
Since the request is a `POST` now, it should have the secret included. Currently requests from the worker fail authentication because we only allow `GET`s through without a secret.
=> Fix worker authentication

cmd/migration-managerd/internal/api/daemon.go, cmd/migration-managerd/internal/api/workers.go, go.mod, go.sum, internal/migratekit/nbdcopy/nbdcopy.go, internal/migratekit/nbdkit/builder.go, internal/migratekit/nbdkit/server.go, internal/server/sys/os.go, internal/source/vmware_linux.go, internal/target/common.go, internal/target/incus.go, internal/target/interface.go, internal/util/archive.go, internal/util/concurrent.go, internal/util/github.go, internal/util/paths.go, internal/version/version.go, internal/worker/linux.go, internal/worker/windows.go
Closes #126
Closes #87 
On batch start, creates `<target>_<pool>_<version>_worker.tar.gz` for each newly encountered target & storage pool combo, and imports it as a storage pool volume backup on the Incus target, if it doesn't exist already.
* If the volume already exists, it will be re-used, without creating a new tarball to import.
* If the tarball for the current migration-manager version already exists for the given pool in the given target, it will be re-used, without creating a new image with the VMware VIX tarball.
* If the raw image for the current migration-manager already exists, it will not be re-fetched from github.
=> Build migration backup volume

cmd/migration-managerd/internal/api/workers.go, internal/target/incus.go
* Run instance creation for multiple batches concurrently. Previously, only instances within 1 batch were created concurrently.
* Fallback to the `default` network if no additional network configuration is defined. This avoids the need to set a JSON config on the network before starting a batch. Obviously instance creation will still fail if the `default` network doesn't exist.
=> Misc improvements

cmd/migration-managerd/internal/api/api_batch.go, cmd/migration-managerd/internal/api/workers.go, internal/server/sys/os.go
* Checks for `virtio-win*.iso` in `/var/cache/migration-manager` and downloads it from its source if not found. 
Since `ensureISOImagesExistInStoragePool` now tries to fetch all missing files (except the vmware tarball), it has been split off from `validateForQueue` as it doesn't validate any existing state anymore and only needs to run before a batch commences instance creation.
=> Download latest virtio win ISO from its source

cmd/migration-managerd/internal/api/api.go
As of go `1.24`, `http.Serve` with TLS requires explicit declaration of supported protocols, and will not implicitly fallback to `http/1.1`. Since we're always using TLS, we might as well support both http/2 and http/1.1.
=> Explicitly support http/2

cmd/migration-managerd/internal/api/workers.go, internal/server/sys/os.go
Sets a `QUEUED` batch message to `Downloading Artifacts` if we need to download (or upload to the target) any resources prior to instance creation.
Happens under the following conditions:
* No base image volume corresponding to the migration manager version exists on the target
* A windows VM is part of the batch, and no virtio drivers ISO can be found
* In this case, we first need to check for existence of the actual ISO in `/var/cache/migration-manager` because we don't actually know the full name of the ISO including its version to check against storage volumes.
=> Set status message if downloads are needed

ui/src/components/ModalWindow.tsx, ui/src/components/TLSFingerprintConfirmModal.tsx, ui/src/css/index.css
1. Added a red "Cancel" button to the fingerprint modal window.
2. Wrapped long words to prevent overflow.
=> ui: Fingerprint modal window improvements

cmd/migration-manager/internal/cmds/network.go, cmd/migration-managerd/internal/api/api_network.go, cmd/migration-managerd/internal/api/workers.go, internal/db/update.go, internal/migration/network_model.go, internal/migration/network_service_test.go, internal/migration/repo/sqlite/entities/network.mapper.go, internal/properties/definitions.go, internal/properties/instance_properties.yaml, internal/source/properties_test.go, internal/source/vmware.go, shared/api/network.go
This allows us to parse distributed port groups from VMware. 
* The keys in the instance properties now support comma-delimited alternatives to the first key. The first matching key set will be used.
* For now, this is used for the network ID, which lives in different places according to the NIC type.
* The NIC network is now the full inventory path of the network
* The NIC inventory path (as `Location`) is now included in the networks API and CLI
* Modifying the network name is no longer supported. This didn't make sense anyway as the periodic sync could overwrite it.
I wanted to try replacing the network ID with the UUID from the vCenter URL, but I can't seem to find the actual UUID  on either the VM or global network API, so I kept it as is for now.
There's also the added issue of ESXI …
=> Add distributed port group support

ui/index.html, ui/src/components/DataTable.tsx, ui/src/components/InstanceDataTable.tsx, ui/src/components/Sidebar.tsx, ui/src/pages/Batch.tsx, ui/src/pages/Source.tsx, ui/src/pages/Target.tsx
- Title change: "Migration manager" → "Migration Manager"
- General UI
- Stretch tables horizontally when space is available
- Sources and Targets view
- Hide the fingerprint from the list
- Instances view
- Hide the UUID column
- Make the source a link to the source detail page
- Make the location a link to the instance detail page
=> ui: Minor layout fixes

cmd/migration-manager/internal/cmds/batch.go, cmd/migration-managerd/internal/api/api_batch.go, cmd/migration-managerd/internal/api/workers.go, internal/db/update.go, internal/migration/batch_model.go, internal/migration/batch_service.go, internal/migration/batch_service_test.go, internal/migration/instance_model.go, internal/migration/queue_ports.go, internal/migration/queue_service.go, internal/migration/queue_service_mock_gen_test.go, internal/migration/queue_service_test.go, internal/migration/repo/middleware/queue_slog_gen.go, internal/migration/repo/mock/queue_repo_mock_gen.go, internal/migration/repo/sqlite/entities/batch.mapper.go, internal/migration/repo/sqlite/queue.go, shared/api/batch.go
Closes #157
Batches can have a list of constraints now.
Each constraint has the following fields:
Name | Description
:-- | :--
name (required)  | name of the constraint
description | description of the constraint
include_expression (required) | expression to match instances
max_concurrent_instances | maximum number of instances matching the constraint that can be in the final migration steps
min_instance_boot_time | minimum time it takes for an instance to boot. The migration window chosen must last at least this long, plus buffer of 1 minute*
*We should add an override per-instance to increase the buffer time once we assign instances to a migration window.
Constraints will be checked in order. The first constraint that an instance matches against will apply to it. If no constraints match …
=> Add Batch Constraints

.github/workflows/vulncheck.yml, go.sum
GH action for govulncheck failed: https://github.com/breml/migration-manager/actions/runs/14966207374/attempts/1
Error message:
```
-: # libguestfs.org/libnbd
Package libnbd was not found in the pkg-config search path.
Perhaps you should add the directory containing `libnbd.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libnbd', required by 'virtual:world', not found
Package 'libnbd', required by 'virtual:world', not found
Package 'libnbd', required by 'virtual:world', not found
Package 'libnbd', required by 'virtual:world', not found
Package 'libnbd', required by 'virtual:world', not found
````
I looks like an issue with `libnbd`. Therefore I added installation of `libnbd-dev` before `govulncheck` is executed in GH action.
=> govulncheck: Attempt to fix failed GH action

ui/src/api/instances.tsx, ui/src/components/BatchForm.test.tsx, ui/src/components/BatchForm.tsx, ui/src/components/BatchOverview.tsx, ui/src/components/InstanceDataTable.tsx, ui/src/components/InstanceOverrides.tsx, ui/src/components/InstanceOverview.tsx, ui/src/components/MigrationWindowsWidget.test.tsx, ui/src/components/MigrationWindowsWidget.tsx, ui/src/pages/Batch.tsx, ui/src/types/batch.d.ts, ui/src/types/instance.d.ts, ui/src/util/instance.test.ts, ui/src/util/instance.ts
1. Fixes after API changes
- Removed `createInstanceOverride` – only `PUT` is supported for instance creation
- Added `source_type` field to instance
- Reorganized fields in `Batch` and `Instance` models
3. Support for multiple migration windows
**Screenshots**
=> ui: Support for multiple migration windows

cmd/migration-managerd/internal/api/workers.go, internal/migratekit/nbdcopy/nbdcopy.go, internal/migratekit/target/disk.go, internal/migratekit/vmware/change_id.go, internal/migratekit/vmware_nbdkit/vmware_nbdkit.go, internal/properties/definitions.go, internal/source/vmware.go, internal/target/incus.go, shared/api/properties.go
* Add support for syncing multiple disks to an Incus target.
* VMs with raw disks, shared disks, or disks without snapshot capabilities are automatically disabled upon detection, and a warning is logged, indicating the VM, its offending disk, and the reason for the lack of support. If this is manually overridden, the VM can be migrated and those disks will be ignored.
* Disk properties now have a `supported` field that shows whether a detected disk supports migration. This was done so those disks can still be used for filtering purposes.
* Worker timeouts don't result in a total failure anymore. Now it's just a message, and if the worker reports back later, the migration will continue where it left off.
The target instance is created first, so that the scheduler can place it, and …
=> Multiple disk support

cmd/migration-manager/internal/cmds/network.go, cmd/migration-manager/internal/cmds/queue.go, cmd/migration-managerd/internal/api/api_batch.go, cmd/migration-managerd/internal/api/api_queue.go, cmd/migration-managerd/internal/api/sync.go, cmd/migration-managerd/internal/api/workers.go, internal/migration/batch_model.go, internal/migration/batch_service.go, internal/migration/instance_model.go, internal/migration/queue_service.go, internal/source/vmware.go, internal/target/incus.go, internal/worker/windows.go, shared/api/queue.go
Closes #218 
Closes #223 
* Properly add virtio-win ISO to all cluster members if pool is not remote
* Properly check `name`, `location`, and `background_import` for updates upon sync
* Properly handle source param in network CLI
* Fix testing mode for errored/running batches
* Use `instanceName-diskN` for additional volumes
* Support all Windows versions that distrobuilder supports
* If a network is of an NSX type, try to re-use its network name (excluding spaces, replaced with hyphens)
---
* Add BLOCKED migration state, which occurs if an instance has `DisableMigration` set when its batch starts
* Allow manually removing queue entries in state BLOCKED, FINISHED, or ERROR
* Before beginning target instance creation, check if any blocked instances can be unblocked.
* Set …
=> Misc fixes

cmd/migration-manager-worker/internal/worker/worker.go, internal/target/incus.go, internal/worker/linux.go, internal/worker/scripts/add-udev-network-rules.sh
Since we don't actually attach the nics at the worker step, put their mac addresses in a user config key so we can base the udev rules on those.
=> Fix network interface name assignment

cmd/migration-manager/internal/cmds/queue.go, cmd/migration-managerd/internal/api/api_queue.go, cmd/migration-managerd/internal/api/sync.go, cmd/migration-managerd/internal/api/workers.go, internal/db/update.go, internal/migration/instance_service.go, internal/migration/queue_model.go, internal/migration/queue_service.go, internal/migration/queue_service_test.go, internal/migration/repo/sqlite/entities/queue.mapper.go, internal/queue/handler.go, internal/source/vmware.go, shared/api/queue.go
* Daemon will now instruct the worker to restart imports if the worker crashes for some reason. This is accomplished by storing the last response we received from the worker and using that to judge what state it's in.
* Rather than showing an ominous "timed out waiting for worker" message if the worker takes a long time to respond, the raw timestamp of the last worker response is now part of the queue entry API object, so UI/CLI can handle it directly
* Adds more descriptive migration status messages
* If we encounter an error after powering off the source VM, we now try to start it back up
=> Error recovery

cmd/migration-manager/internal/cmds/batch.go, cmd/migration-managerd/internal/api/api_batch.go, cmd/migration-managerd/internal/api/daemon.go, cmd/migration-managerd/internal/api/workers.go, internal/db/update.go, internal/migration/batch_model.go, internal/migration/batch_service.go, internal/migration/instance_ports.go, internal/migration/instance_service.go, internal/migration/instance_service_mock_gen_test.go, internal/migration/repo/sqlite/entities/batch.mapper.go, shared/api/batch.go
* Time that the batch initially started is now recorded in the database
* Maximum retry count is added to batches, defaults to 5 in the CLI. If post-migration steps fail for any instance for any reason, it will be retried in 10s (when the next post-migration periodic task runs). After this many retries, the instance will be set to errored, and the source VM will be restarted.
* For testing, we had disabled instance cleanup on initial creation errors. Now this is tied to the `MIGRATION_MANAGER_TESTING` environment variable. If it is set, then instances will not be cleaned up and the first error will cause migration to stop. Otherwise, instances and volumes created on the target will be cleaned up, and creation will be tried again.
=> Add batch start time and max retries

cmd/migration-manager/internal/cmds/instance_override.go, internal/migration/instance_model.go, internal/migration/instance_service.go, internal/migration/instance_service_test.go, internal/source/vmware.go, shared/api/instance_override.go
Before, we used to set `DisableMigration` if we deemed an instance unfit for migration by default, but this can cause issues if a re-sync fixes those issues, causing us to lose context of who actually set `DisableMigration`.
Instead, all the reasons that an instance can be omitted from migration are now handled by the `DisabledReason` method. 
If a user wants to ignore these restrictions, there is now an  `IgnoreRestrictions` instance override flag.  If set to true by the user, then the instance will be considered eligible for migration regardless of any internal restrictions like unsupported disks, or lack of background import. 
`IgnoreRestrictions` will not be able to bypass `DisableMigration` if set to true, which should now only happen explicitly by the user as well.
=> Change default instance restriction handling

cmd/migration-managerd/internal/api/api_instance.go, cmd/migration-managerd/internal/api/api_queue.go, internal/migration/instance_model.go, internal/migration/repo/sqlite/entities/instance.mapper.go
Closes #286 
We can't do this at the DB level, since for instances the secondary field we want to sort on is in a json blob, and for queue entries, is not in the db at all.
=> API sorting

cmd/migration-managerd/internal/api/api.go, cmd/migration-managerd/internal/api/api_1.0.go, cmd/migration-managerd/internal/api/api_incus_os.go
Migration Manager uses http.ServeMux which panics with wildcard paths.
=> Fix Incus OS Proxy

cmd/migration-managerd/internal/api/api_queue.go, cmd/migration-managerd/internal/api/sync.go, cmd/migration-managerd/internal/api/workers.go, internal/properties/instance_properties.yaml, internal/properties/names.go, internal/source/properties_test.go, internal/source/vmware.go, internal/target/incus.go, shared/api/properties.go
* Source VM will only be restarted if its last source sync state was running.
* Target VM will only be started upon completion if its last source sync state was running.
* Adds a 1s sleep to the incus agent ready check
=> Keep track of initial power state

internal/migration/batch_model.go
Fixes the 500 error when listing queue entries with expired migration windows.
This will get caught by the API and skipped, so we won't assign a migration window. 
The side-effect here is that if all migration windows have expired, queue entries will continue waiting forever. I think this is fine since in the future we plan to allow appending migration windows to running batches.
=> internal/migration: Send 404 if all windows expired

internal/source/vmware.go, internal/target/incus.go
Closes #302 
Since this is highly VMware specific, the property is added as the key `vmware.resource_pool` to `properties.config`. 
It appears VM resource pools have their own full location paths: `/DC0/host/DC0_C0/Resources`. I have not supported this directly  yet, instead just appending the suffix (pool name) to the `vmware.resource_pool` key. 
My assumption for now is the datacenter will be the same as the VM, and thus can be deduced from the VM's location path anyway. It would be odd to me if you can place VMs from datacenter 1 in resource pools from datacenter 2, but I suppose we'll see if this is a possibility down the line. 
Resource pools are only supported on vcenter (not ESXI) sources, and if any errors are encountered, they will be logged and the VM will be recorded without …
=> Add resource pools to VM properties

cmd/migration-managerd/internal/config/config.go
If the config file doesn't exist, we were returning a totally empty config which then failed the server port check at startup.
=> Properly set default config when no config file exists

cmd/migration-managerd/internal/api/api_batch.go, cmd/migration-managerd/internal/api/migration_test.go, cmd/migration-managerd/internal/api/sync.go, cmd/migration-managerd/internal/api/workers.go, internal/db/update.go, internal/migration/batch_model.go, internal/migration/instance_model.go, internal/migration/instance_service.go, internal/migration/repo/sqlite/entities/batch.mapper.go, internal/source/vmware.go, shared/api/batch.go
Adds a set of overrides to how we determine if an instance is restricted (migration is disabled) per batch.
* `allow_unknown_os`: In case the guest agent is missing or the OS type is otherwise unknown to migration manager
* `allow_no_ipv4`: In case the guest agent is missing, or no IPv4 address could be determined for any NIC
* `allow_no_background_import`: In case change tracking appears to be missing
=> Batch instance restriction overrides

cmd/migration-managerd/internal/api/api_1.0.go, cmd/migration-managerd/internal/api/api_batch.go, cmd/migration-managerd/internal/api/workers.go, internal/migration/batch_model.go, internal/migration/batch_ports.go, internal/migration/batch_service.go, internal/migration/batch_service_mock_gen_test.go, internal/migration/batch_service_test.go, internal/migration/instance_service.go, internal/migration/queue_model.go, internal/migration/repo/middleware/batch_slog_gen.go, internal/migration/repo/mock/batch_repo_mock_gen.go, internal/migration/repo/sqlite/batch.go, internal/migration/source_service.go, internal/target/incus.go, internal/target/interface.go, internal/target/mock_gen.go
* Updates CleanupVM to check for either the worker volume or `user.migration_source` depending on when it's called, so we don't remove VMs from the target unexpectedly.
* Adds the internal concept of a "committed" queue entry, which maps to states that occur after a request is initiated to power the source VM off.
* Adds `/1.0/batches/{name}/reset` to return a batch to `DEFINED` state and clean up all VMs currently being created or undergoing background sync. This is only possible if no queue entries in the batch are currently "committed". 
* Allows modifying batch parameters while the batch is running:
* Placement and assigned instances cannot be changed
* New migration windows can be appended, but existing windows cannot be modified
* Constraints that do not match any queue entry that …
=> Update and reset running batches

cmd/migration-manager-worker/worker_test.go, cmd/migration-manager/internal/cmds/artifacts.go, cmd/migration-managerd/internal/api/api_artifacts.go, cmd/migration-managerd/internal/api/migration_test.go, internal/migration/artifact_model.go, internal/migration/artifact_service_test.go, shared/api/artifacts.go
* Renames `ArtifactProperties` to `ArtifactPut` to make it clear this is what should be used on the `PUT` endpoint.
* Removes the `name` query parameter on the upload API for now because we only support one pre-defined filename at the moment. This can be added back once we need to consider handling multiple files per artifact.
=> Artifact changes

cmd/migration-manager-worker/internal/worker/worker.go, cmd/migration-manager-worker/worker_test.go, cmd/migration-manager/internal/cmds/artifacts.go, cmd/migration-managerd/internal/api/api_artifacts.go, internal/db/update.go, internal/migration/artifact_model.go, internal/migration/artifact_service_test.go, internal/migration/repo/sqlite/entities/artifact.mapper.go, shared/api/artifacts.go
Closes #332 
* Moves `properties` inline with the main `ArtifactPost` struct to make things consistent with other APIs
* Adds `last_updated` field to Artifact object returned from API. It's updated on each database write via`Create` or `Update`.
* Worker no longer re-imports artifact files each time it receives a new command. It now keeps an in-memory record of each UUID's `last_updated` date, and only re-imports the artifact file if no local file is found, or if the cached last_updated value for a particular UUID does not match the value returned from the API. Since we don't perform cleanup in between commands anymore, cleanup is executed whenever the worker starts or stops.
@presztak The UI should be updated for the new `POST` payload, and objects returned from `GET`.
=> Add `last_updated` to artifacts

cmd/migration-manager/internal/cmds/artifacts.go
The `remove` command was displaying as `export`:
Before:
```
migration-manager artifact --help
Available Commands:
export      Export an artifact by its UUID
export      Remove an artifact file
list        List artifacts
show        Show an artifact by its UUID
upload      Upload an artifact file
```
After:
```
migration-manager artifact --help
Available Commands:
export      Export an artifact by its UUID
list        List artifacts
remove      Remove an artifact file
show        Show an artifact by its UUID
upload      Upload an artifact file
```
=> Fix remove command typo
