worker/Makefile
worker/mkosi.extra/usr/lib/systemd/system/opt.mount
worker/mkosi.extra/usr/lib/systemd/system/seed-unpack.service

worker: Add logic to unpack seed partition (for VIX)

---

cmd/migration-manager-worker/internal/worker/worker.go
cmd/migration-manager-worker/worker_test.go
cmd/migration-managerd/internal/api/api_1.0.go
cmd/migration-managerd/internal/api/api_queue.go
internal/migration/queue_ports.go
internal/migration/queue_service.go
internal/migration/queue_service_mock_gen_test.go
internal/migration/queue_service_test.go

Use POST for non-idempotent PUT endpoints

---

ui/src/App.tsx
ui/src/api/sources.tsx
ui/src/api/targets.tsx
ui/src/components/SourceForm.test.tsx
ui/src/components/SourceForm.tsx
ui/src/components/TargetForm.test.tsx
ui/src/components/TargetForm.tsx
ui/src/pages/Source.tsx
ui/src/pages/SourceConfiguration.tsx
ui/src/pages/SourceCreate.tsx
ui/src/pages/SourceDetail.tsx
ui/src/pages/SourceOverview.tsx
ui/src/pages/Target.tsx
ui/src/pages/TargetConfiguration.tsx
ui/src/pages/TargetCreate.tsx
ui/src/pages/TargetDetail.tsx
ui/src/pages/TargetOverview.tsx
ui/src/types/source.d.ts
ui/src/types/target.d.ts
ui/src/util/response.ts
ui/src/util/source.ts
ui/src/util/target.ts

ui: Add support for create/update/delete of source and target objects

---

ui/src/components/BatchActions.tsx
ui/src/components/BatchDeleteModal.tsx
ui/src/components/ModalWindow.tsx
ui/src/pages/BatchDetail.tsx
ui/src/util/batch.ts

ui: Allow starting and stopping batches from overview page

---

ui/src/components/SourceForm.test.tsx
ui/src/components/SourceForm.tsx
ui/src/components/TLSFingerprintConfirmModal.tsx
ui/src/components/TargetForm.test.tsx
ui/src/components/TargetForm.tsx
ui/src/pages/SourceConfiguration.tsx
ui/src/pages/SourceCreate.tsx
ui/src/pages/TargetConfiguration.tsx
ui/src/pages/TargetCreate.tsx

ui: Better handle server certificate workflow

---

ui/src/components/PasswordField.tsx
ui/src/components/SourceForm.tsx

Adds a new password input component with show/hide functionality. This component is now used in the Source view.

ui: Add show/hide toggle to password field

---

internal/migration/batch_service.go
internal/util/environment.go

Add `MIGRATION_MANAGER_TESTING` environment variable

---

cmd/migration-managerd/internal/api/sync.go

Temporary measure to get around duplicate network IDs. 
It's a bit inefficient in that we first validate and create instance records, only to delete them within the same transaction if we determine they are using a network with a duplicate ID, but this lets us still catch other errors associated with recording those instances.

Skip networks with duplicate IDs and their associated instances

---

ui/src/components/InstanceOverrides.tsx
ui/src/components/KeyValueWidget.test.tsx
ui/src/components/KeyValueWidget.tsx
ui/src/css/index.css
ui/src/css/keyValueWidget.css
ui/src/types/instance.d.ts

ui: Add config key/value overrides

---

cmd/migration-managerd/internal/api/api_instance.go
ui/src/api/instances.tsx
ui/src/components/BatchForm.test.tsx
ui/src/components/BatchForm.tsx
ui/src/css/index.css
ui/src/pages/Instance.tsx
ui/src/util/batch.ts
ui/src/util/response.ts

Support for live validation

---

ui/src/components/DataTable.tsx

ui: Show total entry count in table

---

ui/package.json
ui/src/components/BatchForm.tsx
ui/src/components/MigrationWindowsWidget.test.tsx
ui/src/components/MigrationWindowsWidget.tsx
ui/src/main.tsx
ui/src/test/setup.ts
ui/src/util/date.test.ts
ui/src/util/date.ts
ui/yarn.lock

Closes: [#219](https://github.com/FuturFusion/migration-manager/issues/219)

ui: Use datepicker for datetime fields

---

ui/src/components/SourceForm.test.tsx
ui/src/components/SourceForm.tsx
ui/src/components/TargetForm.test.tsx
ui/src/components/TargetForm.tsx
ui/src/pages/SourceOverview.tsx
ui/src/pages/TargetOverview.tsx
ui/src/types/source.d.ts
ui/src/types/target.d.ts

ui: Add support for concurrency limits

---

internal/migration/source_service.go
internal/migration/target_service.go

Initial PR still had something I put in to debug the cache, making it always reset to 1 entry.

internal/migration: Fix removing from cache

---

cmd/migration-managerd/internal/api/workers.go
internal/target/incus.go

internal/target: Pass timeout context to volume creation

---

ui/src/components/InstanceActions.tsx
ui/src/components/InstanceOverrides.tsx
ui/src/types/instance.d.ts

ui: Add support for 'Ignore restrictions' override

---

ui/src/App.tsx
ui/src/api/warnings.tsx
ui/src/components/Sidebar.tsx
ui/src/components/WarningOverview.tsx
ui/src/pages/Warning.tsx
ui/src/pages/WarningDetail.tsx
ui/src/types/warning.d.ts
ui/src/util/warning.ts

ui: Add warnings

---

ui/src/components/InstanceActions.tsx
ui/src/components/InstanceOverview.tsx
ui/src/types/instance.d.ts

ui: Add running state indicator to instance view

---

ui/src/components/InstanceActions.tsx

ui: Show indicator when background import is not supported

---

internal/target/incus.go

internal/target: Unset user.migration keys when not in testing mode

---

ui/src/components/BatchForm.test.tsx
ui/src/components/BatchForm.tsx
ui/src/components/BatchOverview.tsx
ui/src/types/batch.d.ts

ui: Add batch restriction overrides

---

ui/src/App.tsx
ui/src/api/artifacts.tsx
ui/src/components/ArtifactConfiguration.tsx
ui/src/components/ArtifactFileDeleteButton.tsx
ui/src/components/ArtifactFileDownloadButton.tsx
ui/src/components/ArtifactFileUploader.tsx
ui/src/components/ArtifactFiles.tsx
ui/src/components/ArtifactForm.tsx
ui/src/components/ArtifactOverview.tsx
ui/src/components/Sidebar.tsx
ui/src/pages/Artifact.tsx
ui/src/pages/ArtifactCreate.tsx
ui/src/pages/ArtifactDetail.tsx
ui/src/types/artifact.d.ts
ui/src/util/artifact.ts
ui/src/util/instance.ts

ui: Add Artifacts support

---

ui/src/components/BatchForm.test.tsx
ui/src/components/BatchForm.tsx
ui/src/components/BatchOverview.tsx
ui/src/components/InstanceOverrides.tsx
ui/src/components/InstanceOverview.tsx
ui/src/pages/Batch.tsx
ui/src/types/batch.d.ts
ui/src/types/instance.d.ts

1. Adjustments to new Batch structure
2. Allow overriding OS name
3. Add batch sync intervals
Closes: #333

Update batch component to support new config options

---

ui/src/components/ArtifactConfiguration.tsx
ui/src/components/ArtifactForm.tsx
ui/src/components/ArtifactOverview.tsx
ui/src/pages/Artifact.tsx
ui/src/types/artifact.d.ts

ui: Embed fields from ArtifactProperties into Artifact
